//
// Created by 11896 on 11/10/2024.
//

#ifndef BROADWAY_SIMULATION_FASTFORWARDCOMMAND_HPP
#define BROADWAY_SIMULATION_FASTFORWARDCOMMAND_HPP


class FastForwardCommand {

};


#endif //BROADWAY_SIMULATION_FASTFORWARDCOMMAND_HPP
