//
// Created by 11896 on 11/10/2024.
//

#ifndef BROADWAY_SIMULATION_MOUSEINTERACTIONCOMMAND_HPP
#define BROADWAY_SIMULATION_MOUSEINTERACTIONCOMMAND_HPP


class MouseInteractionCommand {

};


#endif //BROADWAY_SIMULATION_MOUSEINTERACTIONCOMMAND_HPP
