//
// Created by 11896 on 11/10/2024.
//

#ifndef BROADWAY_SIMULATION_RENDERARTISTSCOMMAND_HPP
#define BROADWAY_SIMULATION_RENDERARTISTSCOMMAND_HPP


class RenderArtistsCommand {

};


#endif //BROADWAY_SIMULATION_RENDERARTISTSCOMMAND_HPP
