//
// Created by 11896 on 23/10/2024.
//

#ifndef BROADWAY_SIMULATION_FILEDIALOGMODULE_HPP
#define BROADWAY_SIMULATION_FILEDIALOGMODULE_HPP


class FileDialogModule {

};


#endif //BROADWAY_SIMULATION_FILEDIALOGMODULE_HPP
